import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

export function transformSvg(source) {
  const vb = /viewBox="([^"]+)"/.exec(source);
  if (!vb) throw new Error('SVG missing viewBox');
  let inner = source
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '');
  inner = inner
    .replace(/id="([^"]+)"/g, 'id="__BP__$1"')
    .replace(/url\(#([^)]+)\)/g, 'url(#__BP__$1)')
    .replace(/href="#([^"]+)"/g, 'href="#__BP__$1"');
  return { viewBox: vb[1], markup: inner.trim() };
}

export function titleCase(id) {
  return id.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
}

function buildModule(dir, category) {
  const files = readdirSync(dir).filter((f) => f.endsWith('.svg')).sort();
  const entries = files.map((f) => {
    const id = basename(f, '.svg');
    const { viewBox, markup } = transformSvg(readFileSync(join(dir, f), 'utf8'));
    return [id, { id, name: titleCase(id), category, viewBox, markup }];
  });
  return [
    '// AUTO-GENERATED by scripts/build-assets.mjs — do not edit. Run `npm run assets`.',
    'export interface AssetDef {',
    '  id: string; name: string; category: string; viewBox: string; markup: string;',
    '}',
    `export const ASSETS: Record<string, AssetDef> = ${JSON.stringify(Object.fromEntries(entries), null, 2)};`,
    'export const ASSET_LIST: AssetDef[] = Object.values(ASSETS);',
    '',
  ].join('\n');
}

const isMain = process.argv[1] && import.meta.url.endsWith(basename(process.argv[1]));
if (isMain) {
  mkdirSync('src/generated', { recursive: true });
  writeFileSync('src/generated/assets.ts', buildModule('assets/graphics', 'graphics'));
  console.log(`Wrote src/generated/assets.ts`);
}
